<Project>
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>14</LangVersion>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
        <AnalysisMode>All</AnalysisMode>
    </PropertyGroup>

    <ItemGroup>
        <GlobalAnalyzerConfigFiles Include="$(MSBuildThisFileDirectory).globalconfig" />
        <PackageReference Include="Roslynator.Analyzers" Version="4.*">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>analyzers</IncludeAssets>
        </PackageReference>
    </ItemGroup>
</Project>