using Infrastructure.MasterAccess.Http.Tenants;
using Infrastructure.MasterAccess.Security;
using Microsoft.Extensions.Options;
using NSubstitute;
using Shared.Application.Ports;
using Shared.Results.Errors;
using Shouldly;
using Xunit;

namespace UnitTests.Infrastructure;

public sealed class AesConnectionStringDecryptorTests
{
    private const string Plain = "Server=srv;Database=acme_db;User Id=sa;Password=p@ss;";

    private static AesConnectionStringDecryptor CreateSut(string passphrase) =>
        new(
            Options.Create(new TenantInfoClientSettings { ConnectionStringKey = passphrase }),
            Substitute.For<ILoggerPort<AesConnectionStringDecryptor>>());

    [Fact]
    public void Decrypt_WhenCipherProducedWithSamePassphrase_ReturnsPlaintext()
    {
        var cipher = AesTestCrypto.Encrypt(Plain);
        var sut = CreateSut(AesTestCrypto.Passphrase);

        var result = sut.Decrypt(cipher);

        result.IsSuccess.ShouldBeTrue();
        result.Value.ShouldBe(Plain);
    }

    [Fact]
    public void Decrypt_RealNodeProducedVector_ReturnsPlaintext()
    {
        // Golden vector generated by the tenant-resolver service's exact crypto (Node:
        // SHA-256(passphrase) key, random IV, "{ivHex}:{cipherHex}" lowercase hex, AES-256-CBC/PKCS7).
        // Locks the cross-language interop contract and covers lowercase hex input.
        const string nodeCipher =
            "0d348250ed2afdefd61cb3c3fc2aed49:"
            + "1c21cb9447d5a2badf4203cc3a5d3edc966b32f330153c9ae23563f8068e597d"
            + "e3fe97867f50de7c4cf5f392be8982d97b818ba6e04c8e01262c50fc8518cde1"
            + "8e6b2ae2052944dba3dc0f407b2b5a80";
        const string expected = "Server=tcp:10.0.0.1,1433;Database=tenant_acme;User Id=app;Password=P@ss;";
        var sut = CreateSut(AesTestCrypto.Passphrase);

        var result = sut.Decrypt(nodeCipher);

        result.IsSuccess.ShouldBeTrue();
        result.Value.ShouldBe(expected);
    }

    [Fact]
    public void Decrypt_WithWrongPassphrase_DoesNotRecoverPlaintext()
    {
        var cipher = AesTestCrypto.Encrypt(Plain);
        var sut = CreateSut("a-different-passphrase");

        var result = sut.Decrypt(cipher);

        // Either fails (bad PKCS7 padding) or yields garbage — but never the original secret.
        (result.IsFailure || result.Value != Plain).ShouldBeTrue();
    }

    [Theory]
    [InlineData("")]                          // empty
    [InlineData("   ")]                       // blank
    [InlineData("nonsense-without-separator")] // no ':' separator
    [InlineData(":00112233")]                 // empty IV half
    [InlineData("00112233:")]                 // empty ciphertext half
    [InlineData("zz:0011")]                   // invalid hex
    [InlineData("00112233:44556677")]         // valid hex but IV is not 16 bytes
    public void Decrypt_WhenPayloadMalformed_ReturnsInternalError(string cipher)
    {
        var sut = CreateSut(AesTestCrypto.Passphrase);

        var result = sut.Decrypt(cipher);

        result.IsFailure.ShouldBeTrue();
        result.Error.Type.ShouldBe(ErrorType.Internal);
    }
}
