name: CD — Dev

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    uses: ./.github/workflows/_deploy.yml
    with:
      environment: dev
      eks_cluster: q10-dev-eks
    secrets: inherit
